### ISSUE TITLE
General schematic and board review feedback

### ISSUE THREAD

**Issue by rjehangir** [project-hermes/hermes-board#1]
Hey, this is off to a great start! Nice work. I have a bunch of feedback and suggestions. My last comment is something I just noticed and is probably most critical.

**Schematic and Component Choices:**

1. The LED current limiting resistors are 10k, leaving 0.33mA for each LED. The chosen LEDs will not really light up at that current. Since this device is low power, I would suggest a much more efficient LED like [this one](https://www.digikey.com/product-detail/en/kingbright/APTD1608LVBC-D/754-1948-1-ND/5177478) and use appropriate resistors to limit it to maybe 1mA, which should still get you about 30 mcd brightness. That would be `3.3/0.001 = 3.3Kohm` for the resistors.

2. I see a mix of 0402, 0603, and 0805 packages for various parts. As far as I can tell they could mostly be 0603. I would recommend not using 0402 since this is an open source project and we'll want them to be easier to hand-assemble for anyone who's interested in that.

3. This is personal preference, but I prefer to use the resistors and capacitors without any predefined value and then set the value manually. The values will also show up on the schematic then, which would be nice.

4. For the `USER` and `CONFIG` pull-down resistors I'd recommend moving them to be attached to the buttons in the schematic. The current location is confusing.

5. You're going to have to explain this one to me ;-)

![image](https://user-images.githubusercontent.com/968100/55759612-a5403000-5a0e-11e9-80df-746cd3fdbeaa.png)

6. You have the CP2104 USB to serial chip powered by 3.3v power. Since that part is totally unnecessary when the USB cable (and VCC) are connected, I'd power it by VCC. That will reduce power usage when USB is not connected.

7. I know the Quectel GPS data sheet has a transistor reference circuit for resetting the GPS. I really don't think that will be necessary here and you could connect it directly to a microcontroller pin. I'm fine leaving it if you prefer though.

**Board Layout:**

1. The traces are very thin (6 mil). Since there's so much space available I would recommend making them about twice as wide by default. 12 mil is usually my lower limit unless I'm really packing things in.

2. The power (V_BATT, 3.3V) traces absolutely need to be thicker. I know there's not a lot of current on this board, but any minor issue could cause one of these to burn out. I'd suggest 12-16 mil for these if you have space.

3. **Important.** I'm a little confused if this is real, but somewhere between the board outline file I sent you and now the dimensions got scaled up by 25%. The board is supposed to be 2" wide but in these files it is 2.6" wide. That's what Eagle says although the files you uploaded to CircuitHub today show 2" wide on CircuitHub. I'm not sure what's going on but I'm afraid you might have to do all the layout again. I can totally help if we get into a time crunch.

That's all the time I have today. Let me know your thoughts.

-Rusty

**Comment by sonyccd** [comment]
@rjehangir 
see branch re-layout
### Schematic
1. done
2. done
3. done
4. done
5. it is for the boot strapping, see [Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf) page 5
6. done
7. I would like to follow the reffernce as this is open source and we can point to them in future conversations
